plugins {
    id 'com.android.application'
}

android {
    namespace 'in.kaverisweets.app'
    compileSdk 36

    defaultConfig {
        applicationId 'in.kaverisweets.app'
        minSdk 23
        targetSdk 36
        versionCode 4
        versionName '1.0.3'
    }

    signingConfigs {
        release {
            storeFile file("../kaveri-upload-key.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }

        debug {
            applicationIdSuffix '.debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
}
